name: Go CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20

    - name: Install dependencies
      run: go mod tidy

    - name: Lint with golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.50.1

    - name: Run tests
      run: |
        go test ./... -v -coverprofile=coverage.out
        go tool cover -func=coverage.out

    - name: Generate coverage badge
      run: |
        go install github.com/ryanlid/gocov-html@latest
        gocov-html -coverprofile=coverage.out -o coverage.html
        # Upload coverage badge as artifact
        echo "coverage badge generated"
